trigger:
- iac-bicep-templates

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'SUB-TECH-DEMO'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
        --resource-group RG-TEC-DATA-EAD-DEV \
        --template-file biceps/sqldatabase.bicep
    addSpnToEnvironment: true
