# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- iac-bicep-templates
pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'SUB-TECH-DEMO'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
              --resource-group RG-TEC-SA-EAD-UAT \
              --template-file biceps/webapp.bicep
    addSpnToEnvironment: true
